# Generated by Django 4.2 on 2023-04-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField()),
                ('employeeFirstName', models.CharField(max_length=50)),
                ('employeeLastName', models.CharField(max_length=50)),
            ],
        ),
    ]
