# Generated by Django 4.2 on 2023-04-13 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealID', models.IntegerField()),
                ('mealName', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('glutenFreeYN', models.CharField(max_length=1)),
                ('veganYN', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='MealOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('ordertime', models.DateTimeField()),
                ('doneYN', models.CharField(max_length=1)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('mealID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal')),
            ],
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
