# Generated by Django 4.2 on 2023-04-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_mealorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeID',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='mealID',
        ),
    ]
