# Generated by Django 4.2 on 2023-04-13 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_employee_employeeid_remove_meal_mealid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
