# Generated by Django 4.2 on 2023-04-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_employee_employeefirstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeName',
            field=models.CharField(max_length=100),
        ),
    ]
