# Generated by Django 4.2 on 2023-04-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_order_doneyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
