# Generated by Django 4.2 on 2023-04-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.IntegerField()),
                ('employeeFirstName', models.CharField(max_length=50)),
                ('employeeLastName', models.CharField(max_length=50)),
            ],
        ),
    ]
