# Generated by Django 4.2 on 2023-04-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meal_mealorder_delete_meals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealOrder',
            new_name='Order',
        ),
    ]
