# Generated by Django 4.2 on 2023-04-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeFirstName',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeLastName',
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeName',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='employeeID',
            field=models.ForeignKey(db_column='employeeName', on_delete=django.db.models.deletion.CASCADE, to='main.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mealID',
            field=models.ForeignKey(db_column='mealName', on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
    ]
