# Generated by Django 4.2 on 2023-04-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_employee_employeename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='employeeID',
            new_name='employeeName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='mealID',
            new_name='mealName',
        ),
    ]
